#!/usr/bin/env bash
# This script extracts the first frame of the GIFs from the src folder to the destination folder
# It requires ImageMagick

_SRC_PATH=$1
_DEST_PATH=$2
_TRIM=1 # Trim empty space of each icon and the final file?

if [ -z "$2" ]; then
   _DEST_PATH="${_SRC_PATH}/tmp"
fi

# Cleanup previous files
echo "Cleaning up destination folder..."
rm -rf ${_DEST_PATH}
cp -Rp ${_SRC_PATH} ${_DEST_PATH}
cd ${_DEST_PATH}

WIDEST_SRC=0
HIGHEST_SRC=0
WIDEST_DEST=0
HIGHEST_DEST=0

echo "Converting pictures..."
for img in *.gif; do
    W=`identify -format "%w" ${img}[0]`
    H=`identify -format "%h" ${img}[0]`
    if [ ${W} -gt ${WIDEST_SRC} ]
    then
        WIDEST_SRC=${W}
    fi
    if [ ${H} -gt ${HIGHEST_SRC} ]
    then
        HIGHEST_SRC=${H}
    fi


    convert ${img}[0] -coalesce ${img} || exit 1
    if [ ${_TRIM} -eq 1 ]
    then
        mogrify -trim ${img} || exit 1
    fi


    W=`identify -format "%w" ${img}`
    H=`identify -format "%h" ${img}`
    if [ ${W} -gt ${WIDEST_DEST} ]
    then
        WIDEST_DEST=${W}
    fi
    if [ ${H} -gt ${HIGHEST_DEST} ]
    then
        HIGHEST_DEST=${H}
    fi
done

echo "Biggest SRC  picture: ${WIDEST_SRC}x${HIGHEST_SRC} px"
echo "Biggest DEST picture: ${WIDEST_DEST}x${HIGHEST_DEST} px"
echo "DONE!"
exit 0