#!/usr/bin/env bash
# This script extracts all the frames of the GIFs from the src folder to the destination folder
# It requires ImageMagick

_SRC_PATH=$1
_DEST_PATH=$2
_TRIM=1 # Trim empty space of each icon and the final file?

if [ -z "$2" ]; then
   _DEST_PATH="${_SRC_PATH}/tmp"
fi

# Cleanup previous files
echo "Cleaning up destination folder..."
rm -rf ${_DEST_PATH}
cp -Rp ${_SRC_PATH} ${_DEST_PATH}
cd ${_DEST_PATH}

echo "Converting pictures..."
for img in *.gif; do
    img_noext=`basename $img .gif`
    mkdir -p ${img_noext}
    convert ${img} -coalesce ${img_noext}/${img_noext}_%d.gif
    mv ${img} ${img_noext}/${img}
done

if [ ${_TRIM} -eq 1 ]
then
    mogrify -trim *.gif
fi

echo "DONE!"
exit 0