#!/usr/bin/env bash
# This script extracts the first frame of the GIFs from the src folder to the destination folder
# It requires ImageMagick

img=$1 # src image
dest=$2 # destination image
frame=$3 # GIF frame
_TRIM=1 # Trim empty space of each icon and the final file?

if [ -z "$2" ]; then
    echo "Missing destination image file. Aborting."
    exit 1
fi

if [ -z "$3" ]; then
   frame=0
fi

frame_img="${img}[${frame}]"

echo "Converting animated GIF to static ..."
echo "Processing ${img}[${frame}]..."

convert ${frame_img} -coalesce ${dest} || exit 1
if [ ${_TRIM} -eq 1 ]
then
    mogrify -trim ${dest} || exit 1
fi

echo "DONE!"
exit 0