#!/usr/bin/env bash
# Helper for selecting a frame from the animated GIF and saving it into the non-animated folder
# It requires ImageMagick

# $1 : pokemon file name, without ext.
# $2 : GIF frame
# $3 : name of non-animated folder

srcFile="graphics/pokemon/ani-${3}/${1}.gif"
destFile="graphics/pokemon/${3}/${1}.gif"

./scripts/imagemagick/extract-single ${srcFile} ${destFile} $2