#!/usr/bin/env bash
# Helper for selecting a frame from the animated GIF and saving it into the non-animated folder
# This helper does the same from-to all the 8 folders
# It requires ImageMagick

# $1 : pokemon file name, without ext.
# $2 : GIF frame

extractPokemon(){
    srcFile="graphics/pokemon/ani-${3}/${1}.gif"
    destFile="graphics/pokemon/${3}/${1}.gif"
    ./scripts/imagemagick/extract-single ${srcFile} ${destFile} $2
}

extractPokemon $1 $2 front
extractPokemon $1 $2 front-shiny
extractPokemon $1 $2 back
extractPokemon $1 $2 back-shiny