#!/usr/bin/env bash
# This script extracts the given frame of the given GIF to the destination file
# It requires ImageMagick

img=$1 # src image
dest=$2 # destination image
frame=$3 # GIF frame
_TRIM=1 # Trim empty space of each icon and the final file?

if [ -z "$1" ] || [ -z "$2" ] ; then
    echo "Missing required parameters. Aborting."
    exit 1
fi

if [ -z "$3" ]; then
   frame=0
fi

frame_img="${img}[${frame}]"

echo "Converting animated GIF to static ..."
echo "Saving ${img}[${frame}] into ${dest}..."

convert ${frame_img} -coalesce ${dest} || exit 1
if [ ${_TRIM} -eq 1 ]
then
    mogrify -trim ${dest} || exit 1
fi

echo "DONE!"
exit 0