#!/usr/bin/env bash

echo "WARNING! This process will take a couple of hours, please be patient..."
./scripts/frame-extract-all pokemon/ani-front pokemon/ani-front-extracted
./scripts/frame-extract-all pokemon/ani-front-shiny pokemon/ani-front-shiny-extracted
./scripts/frame-extract-all pokemon/ani-back pokemon/ani-back-extracted
./scripts/frame-extract-all pokemon/ani-back-shiny pokemon/ani-back-shiny-extracted