#!/usr/bin/env bash
# This script flips horizontally all PNG images of the destination path
# It requires ImageMagick

_SRC_PATH=$1
_DEST_PATH=$2

if [ -z "$2" ]; then
   _DEST_PATH="${_SRC_PATH}/tmp"
fi

# Cleanup previous files
echo "Cleaning up destination folder..."
rm -rf ${_DEST_PATH}
cp -Rp ${_SRC_PATH} ${_DEST_PATH}
cd ${_DEST_PATH}

echo "Converting pictures..."
mogrify -flop *.png || exit 1
echo "DONE!"
exit 0